### ISSUE TITLE
Namespace for Client model

### ISSUE THREAD

**Issue by yliu163** [socialcast/devise_oauth2_providable#15]
I encountered some namespace conflicts when using the client class. I think it's desirable to specify the namespace for all the Client constant appearing in the code. Thanks.

**Comment by wireframe** [comment]
i have a proposed change for this by using a rails 3.1 mountable engine which will isolate the models into the Devise::Oauth2Providable namespace and all database tables will be prefixed with oauth2.

the changes are available on the mountable-engine if you would care to review.

**Comment by ZenCocoon** [comment]
Looks like you deleted the Clients management, is that not something you like to be included out of the box ?

**Comment by wireframe** [comment]
correct.  i don't forsee this gem supporting client management out of the box.  since client management is highly subject to the needs of each application, it does not seem like a general concern to be included in this gem and it is well outside the scope of the oauth2 spec.

see issue #17 for more discussion.

**Comment by ZenCocoon** [comment]
Makes sense. Thanks for your explanations.
