### ISSUE TITLE
Access permission not saved. Bug or missing feature?

### ISSUE THREAD

**Issue by ZenCocoon** [socialcast/devise_oauth2_providable#19]
As of now, it seems that the provider will not save the access permission, therefore, on each "Sign In" the user will have to accept or deny access.

How to save such authorization in case of acceptance ? Is that a bug or a feature that need to be implemented on top of it ?

Thanks in advance for your enlightenment,
Best regards,
- Sébastien Grosjean - ZenCocoon

**Comment by ZenCocoon** [comment]
I've setup a demo app that can help better understand what I mean : https://github.com/ZenCocoon/testoauth2provider

**Comment by wireframe** [comment]
I am 100% on board with adding this as a feature.  If you have any thoughts on how to best support this, please let me know!

**Comment by ZenCocoon** [comment]
Thanks for your reply, I'll dig through and see how I would see that best.

**Comment by ZenCocoon** [comment]
What would you think about a "Connection" relation, linking User (Devise resource) to Client ?
That seem to be the way used by GitHub and feels clean to me.

**Comment by wireframe** [comment]
i've been reviewing the oauth2 spec a _lot_ and it seems like this is only an issue with the implicit grant_type flow.

if you use the authorization_code grant_type flow, you exchange your authorization code for an access token _and_ a refresh token as well.  So you don't need to re-authorize the user since you can fetch a new access token via the refresh token.

are you using the implicit flow in your app?

**Comment by ZenCocoon** [comment]
Sorry for the late reply. That makes sense, thanks for the pointer.

I'll dig OmniAuth 1.0 again to see how to rely on the authorization_code grant_type flow. I should be using the implicit grant_type flow so far.
